from arvores.arvore import BSTNode

root = BSTNode()
root.insert(10)
root.insert(7)
root.insert(9)
root.insert(5)
root.insert(20)
root.insert(25)
root.insert(13)
root.insert(2)
print('Pre-ordem:', end=' ')
root.imprimir_pre()
print('\nOrdem central: ', end=' ')
root.imprimir_central()
print('\nTamanho:', root.tamanho())
print('Soma:', root.soma())
print('Altura:', root.altura())
print('Balanceada: ', root.balanceada())
vet = []
root.gerar_lista(vet)
print('Vetor: ', vet)
root.destruir()
root = BSTNode()
